fix: replace app.listen().on in app.js
When I tried to run the code for the app.js in the "An API Server" part of the tutorial, I got this error : 
TypeError: app.listen(...).on is not a function

I am using node v16.13.2 and npm 8.7.0.

I replaced the function causing the error with a working syntax and the app launched correctly.